/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedStudentSearchRouteImport } from './routes/_authenticated/student/search'
import { Route as AuthenticatedStudentResumeRouteImport } from './routes/_authenticated/student/resume'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentFullscreenTestRouteImport } from './routes/_authenticated/student/fullscreen-test'
import { Route as AuthenticatedStudentBookmarksRouteImport } from './routes/_authenticated/student/bookmarks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminVideosIndexRouteImport } from './routes/_authenticated/admin/videos.index'
import { Route as AuthenticatedAdminUniversitiesIndexRouteImport } from './routes/_authenticated/admin/universities.index'
import { Route as AuthenticatedAdminUnitsIndexRouteImport } from './routes/_authenticated/admin/units.index'
import { Route as AuthenticatedAdminTimetablesIndexRouteImport } from './routes/_authenticated/admin/timetables.index'
import { Route as AuthenticatedAdminSubjectsIndexRouteImport } from './routes/_authenticated/admin/subjects.index'
import { Route as AuthenticatedAdminSemestersIndexRouteImport } from './routes/_authenticated/admin/semesters.index'
import { Route as AuthenticatedAdminQuestionsIndexRouteImport } from './routes/_authenticated/admin/questions.index'
import { Route as AuthenticatedAdminPapersIndexRouteImport } from './routes/_authenticated/admin/papers.index'
import { Route as AuthenticatedAdminMaterialsIndexRouteImport } from './routes/_authenticated/admin/materials.index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin/courses.index'
import { Route as AuthenticatedStudentUniversityIdRouteImport } from './routes/_authenticated/student/university.$id'
import { Route as AuthenticatedStudentUnitIdRouteImport } from './routes/_authenticated/student/unit.$id'
import { Route as AuthenticatedStudentSubjectIdRouteImport } from './routes/_authenticated/student/subject.$id'
import { Route as AuthenticatedStudentSemesterIdRouteImport } from './routes/_authenticated/student/semester.$id'
import { Route as AuthenticatedStudentCourseIdRouteImport } from './routes/_authenticated/student/course.$id'
import { Route as AuthenticatedStudentArenaIdRouteImport } from './routes/_authenticated/student/arena.$id'
import { Route as AuthenticatedAdminVideosAddRouteImport } from './routes/_authenticated/admin/videos.add'
import { Route as AuthenticatedAdminUniversitiesAddRouteImport } from './routes/_authenticated/admin/universities.add'
import { Route as AuthenticatedAdminUnitsAddRouteImport } from './routes/_authenticated/admin/units.add'
import { Route as AuthenticatedAdminTimetablesAddRouteImport } from './routes/_authenticated/admin/timetables.add'
import { Route as AuthenticatedAdminSubjectsAddRouteImport } from './routes/_authenticated/admin/subjects.add'
import { Route as AuthenticatedAdminSemestersAddRouteImport } from './routes/_authenticated/admin/semesters.add'
import { Route as AuthenticatedAdminQuestionsAddRouteImport } from './routes/_authenticated/admin/questions.add'
import { Route as AuthenticatedAdminPapersAddRouteImport } from './routes/_authenticated/admin/papers.add'
import { Route as AuthenticatedAdminMaterialsAddRouteImport } from './routes/_authenticated/admin/materials.add'
import { Route as AuthenticatedAdminCoursesAddRouteImport } from './routes/_authenticated/admin/courses.add'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentSearchRoute =
  AuthenticatedStudentSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentResumeRoute =
  AuthenticatedStudentResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentFullscreenTestRoute =
  AuthenticatedStudentFullscreenTestRouteImport.update({
    id: '/fullscreen-test',
    path: '/fullscreen-test',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentBookmarksRoute =
  AuthenticatedStudentBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosIndexRoute =
  AuthenticatedAdminVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesIndexRoute =
  AuthenticatedAdminUniversitiesIndexRouteImport.update({
    id: '/universities/',
    path: '/universities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnitsIndexRoute =
  AuthenticatedAdminUnitsIndexRouteImport.update({
    id: '/units/',
    path: '/units/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimetablesIndexRoute =
  AuthenticatedAdminTimetablesIndexRouteImport.update({
    id: '/timetables/',
    path: '/timetables/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsIndexRoute =
  AuthenticatedAdminSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSemestersIndexRoute =
  AuthenticatedAdminSemestersIndexRouteImport.update({
    id: '/semesters/',
    path: '/semesters/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsIndexRoute =
  AuthenticatedAdminQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPapersIndexRoute =
  AuthenticatedAdminPapersIndexRouteImport.update({
    id: '/papers/',
    path: '/papers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialsIndexRoute =
  AuthenticatedAdminMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentUniversityIdRoute =
  AuthenticatedStudentUniversityIdRouteImport.update({
    id: '/university/$id',
    path: '/university/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentUnitIdRoute =
  AuthenticatedStudentUnitIdRouteImport.update({
    id: '/unit/$id',
    path: '/unit/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentSubjectIdRoute =
  AuthenticatedStudentSubjectIdRouteImport.update({
    id: '/subject/$id',
    path: '/subject/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentSemesterIdRoute =
  AuthenticatedStudentSemesterIdRouteImport.update({
    id: '/semester/$id',
    path: '/semester/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentCourseIdRoute =
  AuthenticatedStudentCourseIdRouteImport.update({
    id: '/course/$id',
    path: '/course/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentArenaIdRoute =
  AuthenticatedStudentArenaIdRouteImport.update({
    id: '/arena/$id',
    path: '/arena/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminVideosAddRoute =
  AuthenticatedAdminVideosAddRouteImport.update({
    id: '/videos/add',
    path: '/videos/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesAddRoute =
  AuthenticatedAdminUniversitiesAddRouteImport.update({
    id: '/universities/add',
    path: '/universities/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnitsAddRoute =
  AuthenticatedAdminUnitsAddRouteImport.update({
    id: '/units/add',
    path: '/units/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimetablesAddRoute =
  AuthenticatedAdminTimetablesAddRouteImport.update({
    id: '/timetables/add',
    path: '/timetables/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsAddRoute =
  AuthenticatedAdminSubjectsAddRouteImport.update({
    id: '/subjects/add',
    path: '/subjects/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSemestersAddRoute =
  AuthenticatedAdminSemestersAddRouteImport.update({
    id: '/semesters/add',
    path: '/semesters/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsAddRoute =
  AuthenticatedAdminQuestionsAddRouteImport.update({
    id: '/questions/add',
    path: '/questions/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPapersAddRoute =
  AuthenticatedAdminPapersAddRouteImport.update({
    id: '/papers/add',
    path: '/papers/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaterialsAddRoute =
  AuthenticatedAdminMaterialsAddRouteImport.update({
    id: '/materials/add',
    path: '/materials/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesAddRoute =
  AuthenticatedAdminCoursesAddRouteImport.update({
    id: '/courses/add',
    path: '/courses/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/bookmarks': typeof AuthenticatedStudentBookmarksRoute
  '/student/fullscreen-test': typeof AuthenticatedStudentFullscreenTestRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/resume': typeof AuthenticatedStudentResumeRoute
  '/student/search': typeof AuthenticatedStudentSearchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/admin/courses/add': typeof AuthenticatedAdminCoursesAddRoute
  '/admin/materials/add': typeof AuthenticatedAdminMaterialsAddRoute
  '/admin/papers/add': typeof AuthenticatedAdminPapersAddRoute
  '/admin/questions/add': typeof AuthenticatedAdminQuestionsAddRoute
  '/admin/semesters/add': typeof AuthenticatedAdminSemestersAddRoute
  '/admin/subjects/add': typeof AuthenticatedAdminSubjectsAddRoute
  '/admin/timetables/add': typeof AuthenticatedAdminTimetablesAddRoute
  '/admin/units/add': typeof AuthenticatedAdminUnitsAddRoute
  '/admin/universities/add': typeof AuthenticatedAdminUniversitiesAddRoute
  '/admin/videos/add': typeof AuthenticatedAdminVideosAddRoute
  '/student/arena/$id': typeof AuthenticatedStudentArenaIdRoute
  '/student/course/$id': typeof AuthenticatedStudentCourseIdRoute
  '/student/semester/$id': typeof AuthenticatedStudentSemesterIdRoute
  '/student/subject/$id': typeof AuthenticatedStudentSubjectIdRoute
  '/student/unit/$id': typeof AuthenticatedStudentUnitIdRoute
  '/student/university/$id': typeof AuthenticatedStudentUniversityIdRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/materials/': typeof AuthenticatedAdminMaterialsIndexRoute
  '/admin/papers/': typeof AuthenticatedAdminPapersIndexRoute
  '/admin/questions/': typeof AuthenticatedAdminQuestionsIndexRoute
  '/admin/semesters/': typeof AuthenticatedAdminSemestersIndexRoute
  '/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/timetables/': typeof AuthenticatedAdminTimetablesIndexRoute
  '/admin/units/': typeof AuthenticatedAdminUnitsIndexRoute
  '/admin/universities/': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/bookmarks': typeof AuthenticatedStudentBookmarksRoute
  '/student/fullscreen-test': typeof AuthenticatedStudentFullscreenTestRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/resume': typeof AuthenticatedStudentResumeRoute
  '/student/search': typeof AuthenticatedStudentSearchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/courses/add': typeof AuthenticatedAdminCoursesAddRoute
  '/admin/materials/add': typeof AuthenticatedAdminMaterialsAddRoute
  '/admin/papers/add': typeof AuthenticatedAdminPapersAddRoute
  '/admin/questions/add': typeof AuthenticatedAdminQuestionsAddRoute
  '/admin/semesters/add': typeof AuthenticatedAdminSemestersAddRoute
  '/admin/subjects/add': typeof AuthenticatedAdminSubjectsAddRoute
  '/admin/timetables/add': typeof AuthenticatedAdminTimetablesAddRoute
  '/admin/units/add': typeof AuthenticatedAdminUnitsAddRoute
  '/admin/universities/add': typeof AuthenticatedAdminUniversitiesAddRoute
  '/admin/videos/add': typeof AuthenticatedAdminVideosAddRoute
  '/student/arena/$id': typeof AuthenticatedStudentArenaIdRoute
  '/student/course/$id': typeof AuthenticatedStudentCourseIdRoute
  '/student/semester/$id': typeof AuthenticatedStudentSemesterIdRoute
  '/student/subject/$id': typeof AuthenticatedStudentSubjectIdRoute
  '/student/unit/$id': typeof AuthenticatedStudentUnitIdRoute
  '/student/university/$id': typeof AuthenticatedStudentUniversityIdRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsIndexRoute
  '/admin/papers': typeof AuthenticatedAdminPapersIndexRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsIndexRoute
  '/admin/semesters': typeof AuthenticatedAdminSemestersIndexRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsIndexRoute
  '/admin/timetables': typeof AuthenticatedAdminTimetablesIndexRoute
  '/admin/units': typeof AuthenticatedAdminUnitsIndexRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/admin/videos': typeof AuthenticatedAdminVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/student/bookmarks': typeof AuthenticatedStudentBookmarksRoute
  '/_authenticated/student/fullscreen-test': typeof AuthenticatedStudentFullscreenTestRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/resume': typeof AuthenticatedStudentResumeRoute
  '/_authenticated/student/search': typeof AuthenticatedStudentSearchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/admin/courses/add': typeof AuthenticatedAdminCoursesAddRoute
  '/_authenticated/admin/materials/add': typeof AuthenticatedAdminMaterialsAddRoute
  '/_authenticated/admin/papers/add': typeof AuthenticatedAdminPapersAddRoute
  '/_authenticated/admin/questions/add': typeof AuthenticatedAdminQuestionsAddRoute
  '/_authenticated/admin/semesters/add': typeof AuthenticatedAdminSemestersAddRoute
  '/_authenticated/admin/subjects/add': typeof AuthenticatedAdminSubjectsAddRoute
  '/_authenticated/admin/timetables/add': typeof AuthenticatedAdminTimetablesAddRoute
  '/_authenticated/admin/units/add': typeof AuthenticatedAdminUnitsAddRoute
  '/_authenticated/admin/universities/add': typeof AuthenticatedAdminUniversitiesAddRoute
  '/_authenticated/admin/videos/add': typeof AuthenticatedAdminVideosAddRoute
  '/_authenticated/student/arena/$id': typeof AuthenticatedStudentArenaIdRoute
  '/_authenticated/student/course/$id': typeof AuthenticatedStudentCourseIdRoute
  '/_authenticated/student/semester/$id': typeof AuthenticatedStudentSemesterIdRoute
  '/_authenticated/student/subject/$id': typeof AuthenticatedStudentSubjectIdRoute
  '/_authenticated/student/unit/$id': typeof AuthenticatedStudentUnitIdRoute
  '/_authenticated/student/university/$id': typeof AuthenticatedStudentUniversityIdRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/materials/': typeof AuthenticatedAdminMaterialsIndexRoute
  '/_authenticated/admin/papers/': typeof AuthenticatedAdminPapersIndexRoute
  '/_authenticated/admin/questions/': typeof AuthenticatedAdminQuestionsIndexRoute
  '/_authenticated/admin/semesters/': typeof AuthenticatedAdminSemestersIndexRoute
  '/_authenticated/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/_authenticated/admin/timetables/': typeof AuthenticatedAdminTimetablesIndexRoute
  '/_authenticated/admin/units/': typeof AuthenticatedAdminUnitsIndexRoute
  '/_authenticated/admin/universities/': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/_authenticated/admin/videos/': typeof AuthenticatedAdminVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/student'
    | '/admin/content'
    | '/admin/users'
    | '/student/bookmarks'
    | '/student/fullscreen-test'
    | '/student/profile'
    | '/student/resume'
    | '/student/search'
    | '/admin/'
    | '/student/'
    | '/admin/courses/add'
    | '/admin/materials/add'
    | '/admin/papers/add'
    | '/admin/questions/add'
    | '/admin/semesters/add'
    | '/admin/subjects/add'
    | '/admin/timetables/add'
    | '/admin/units/add'
    | '/admin/universities/add'
    | '/admin/videos/add'
    | '/student/arena/$id'
    | '/student/course/$id'
    | '/student/semester/$id'
    | '/student/subject/$id'
    | '/student/unit/$id'
    | '/student/university/$id'
    | '/admin/courses/'
    | '/admin/materials/'
    | '/admin/papers/'
    | '/admin/questions/'
    | '/admin/semesters/'
    | '/admin/subjects/'
    | '/admin/timetables/'
    | '/admin/units/'
    | '/admin/universities/'
    | '/admin/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/content'
    | '/admin/users'
    | '/student/bookmarks'
    | '/student/fullscreen-test'
    | '/student/profile'
    | '/student/resume'
    | '/student/search'
    | '/admin'
    | '/student'
    | '/admin/courses/add'
    | '/admin/materials/add'
    | '/admin/papers/add'
    | '/admin/questions/add'
    | '/admin/semesters/add'
    | '/admin/subjects/add'
    | '/admin/timetables/add'
    | '/admin/units/add'
    | '/admin/universities/add'
    | '/admin/videos/add'
    | '/student/arena/$id'
    | '/student/course/$id'
    | '/student/semester/$id'
    | '/student/subject/$id'
    | '/student/unit/$id'
    | '/student/university/$id'
    | '/admin/courses'
    | '/admin/materials'
    | '/admin/papers'
    | '/admin/questions'
    | '/admin/semesters'
    | '/admin/subjects'
    | '/admin/timetables'
    | '/admin/units'
    | '/admin/universities'
    | '/admin/videos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/users'
    | '/_authenticated/student/bookmarks'
    | '/_authenticated/student/fullscreen-test'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/resume'
    | '/_authenticated/student/search'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/admin/courses/add'
    | '/_authenticated/admin/materials/add'
    | '/_authenticated/admin/papers/add'
    | '/_authenticated/admin/questions/add'
    | '/_authenticated/admin/semesters/add'
    | '/_authenticated/admin/subjects/add'
    | '/_authenticated/admin/timetables/add'
    | '/_authenticated/admin/units/add'
    | '/_authenticated/admin/universities/add'
    | '/_authenticated/admin/videos/add'
    | '/_authenticated/student/arena/$id'
    | '/_authenticated/student/course/$id'
    | '/_authenticated/student/semester/$id'
    | '/_authenticated/student/subject/$id'
    | '/_authenticated/student/unit/$id'
    | '/_authenticated/student/university/$id'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/materials/'
    | '/_authenticated/admin/papers/'
    | '/_authenticated/admin/questions/'
    | '/_authenticated/admin/semesters/'
    | '/_authenticated/admin/subjects/'
    | '/_authenticated/admin/timetables/'
    | '/_authenticated/admin/units/'
    | '/_authenticated/admin/universities/'
    | '/_authenticated/admin/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/search': {
      id: '/_authenticated/student/search'
      path: '/search'
      fullPath: '/student/search'
      preLoaderRoute: typeof AuthenticatedStudentSearchRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/resume': {
      id: '/_authenticated/student/resume'
      path: '/resume'
      fullPath: '/student/resume'
      preLoaderRoute: typeof AuthenticatedStudentResumeRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/fullscreen-test': {
      id: '/_authenticated/student/fullscreen-test'
      path: '/fullscreen-test'
      fullPath: '/student/fullscreen-test'
      preLoaderRoute: typeof AuthenticatedStudentFullscreenTestRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/bookmarks': {
      id: '/_authenticated/student/bookmarks'
      path: '/bookmarks'
      fullPath: '/student/bookmarks'
      preLoaderRoute: typeof AuthenticatedStudentBookmarksRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos/': {
      id: '/_authenticated/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AuthenticatedAdminVideosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities/': {
      id: '/_authenticated/admin/universities/'
      path: '/universities'
      fullPath: '/admin/universities/'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/units/': {
      id: '/_authenticated/admin/units/'
      path: '/units'
      fullPath: '/admin/units/'
      preLoaderRoute: typeof AuthenticatedAdminUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/timetables/': {
      id: '/_authenticated/admin/timetables/'
      path: '/timetables'
      fullPath: '/admin/timetables/'
      preLoaderRoute: typeof AuthenticatedAdminTimetablesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects/': {
      id: '/_authenticated/admin/subjects/'
      path: '/subjects'
      fullPath: '/admin/subjects/'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/semesters/': {
      id: '/_authenticated/admin/semesters/'
      path: '/semesters'
      fullPath: '/admin/semesters/'
      preLoaderRoute: typeof AuthenticatedAdminSemestersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions/': {
      id: '/_authenticated/admin/questions/'
      path: '/questions'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/papers/': {
      id: '/_authenticated/admin/papers/'
      path: '/papers'
      fullPath: '/admin/papers/'
      preLoaderRoute: typeof AuthenticatedAdminPapersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materials/': {
      id: '/_authenticated/admin/materials/'
      path: '/materials'
      fullPath: '/admin/materials/'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/university/$id': {
      id: '/_authenticated/student/university/$id'
      path: '/university/$id'
      fullPath: '/student/university/$id'
      preLoaderRoute: typeof AuthenticatedStudentUniversityIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/unit/$id': {
      id: '/_authenticated/student/unit/$id'
      path: '/unit/$id'
      fullPath: '/student/unit/$id'
      preLoaderRoute: typeof AuthenticatedStudentUnitIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/subject/$id': {
      id: '/_authenticated/student/subject/$id'
      path: '/subject/$id'
      fullPath: '/student/subject/$id'
      preLoaderRoute: typeof AuthenticatedStudentSubjectIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/semester/$id': {
      id: '/_authenticated/student/semester/$id'
      path: '/semester/$id'
      fullPath: '/student/semester/$id'
      preLoaderRoute: typeof AuthenticatedStudentSemesterIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/course/$id': {
      id: '/_authenticated/student/course/$id'
      path: '/course/$id'
      fullPath: '/student/course/$id'
      preLoaderRoute: typeof AuthenticatedStudentCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/arena/$id': {
      id: '/_authenticated/student/arena/$id'
      path: '/arena/$id'
      fullPath: '/student/arena/$id'
      preLoaderRoute: typeof AuthenticatedStudentArenaIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/videos/add': {
      id: '/_authenticated/admin/videos/add'
      path: '/videos/add'
      fullPath: '/admin/videos/add'
      preLoaderRoute: typeof AuthenticatedAdminVideosAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities/add': {
      id: '/_authenticated/admin/universities/add'
      path: '/universities/add'
      fullPath: '/admin/universities/add'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/units/add': {
      id: '/_authenticated/admin/units/add'
      path: '/units/add'
      fullPath: '/admin/units/add'
      preLoaderRoute: typeof AuthenticatedAdminUnitsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/timetables/add': {
      id: '/_authenticated/admin/timetables/add'
      path: '/timetables/add'
      fullPath: '/admin/timetables/add'
      preLoaderRoute: typeof AuthenticatedAdminTimetablesAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects/add': {
      id: '/_authenticated/admin/subjects/add'
      path: '/subjects/add'
      fullPath: '/admin/subjects/add'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/semesters/add': {
      id: '/_authenticated/admin/semesters/add'
      path: '/semesters/add'
      fullPath: '/admin/semesters/add'
      preLoaderRoute: typeof AuthenticatedAdminSemestersAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions/add': {
      id: '/_authenticated/admin/questions/add'
      path: '/questions/add'
      fullPath: '/admin/questions/add'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/papers/add': {
      id: '/_authenticated/admin/papers/add'
      path: '/papers/add'
      fullPath: '/admin/papers/add'
      preLoaderRoute: typeof AuthenticatedAdminPapersAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materials/add': {
      id: '/_authenticated/admin/materials/add'
      path: '/materials/add'
      fullPath: '/admin/materials/add'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/add': {
      id: '/_authenticated/admin/courses/add'
      path: '/courses/add'
      fullPath: '/admin/courses/add'
      preLoaderRoute: typeof AuthenticatedAdminCoursesAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCoursesAddRoute: typeof AuthenticatedAdminCoursesAddRoute
  AuthenticatedAdminMaterialsAddRoute: typeof AuthenticatedAdminMaterialsAddRoute
  AuthenticatedAdminPapersAddRoute: typeof AuthenticatedAdminPapersAddRoute
  AuthenticatedAdminQuestionsAddRoute: typeof AuthenticatedAdminQuestionsAddRoute
  AuthenticatedAdminSemestersAddRoute: typeof AuthenticatedAdminSemestersAddRoute
  AuthenticatedAdminSubjectsAddRoute: typeof AuthenticatedAdminSubjectsAddRoute
  AuthenticatedAdminTimetablesAddRoute: typeof AuthenticatedAdminTimetablesAddRoute
  AuthenticatedAdminUnitsAddRoute: typeof AuthenticatedAdminUnitsAddRoute
  AuthenticatedAdminUniversitiesAddRoute: typeof AuthenticatedAdminUniversitiesAddRoute
  AuthenticatedAdminVideosAddRoute: typeof AuthenticatedAdminVideosAddRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminMaterialsIndexRoute: typeof AuthenticatedAdminMaterialsIndexRoute
  AuthenticatedAdminPapersIndexRoute: typeof AuthenticatedAdminPapersIndexRoute
  AuthenticatedAdminQuestionsIndexRoute: typeof AuthenticatedAdminQuestionsIndexRoute
  AuthenticatedAdminSemestersIndexRoute: typeof AuthenticatedAdminSemestersIndexRoute
  AuthenticatedAdminSubjectsIndexRoute: typeof AuthenticatedAdminSubjectsIndexRoute
  AuthenticatedAdminTimetablesIndexRoute: typeof AuthenticatedAdminTimetablesIndexRoute
  AuthenticatedAdminUnitsIndexRoute: typeof AuthenticatedAdminUnitsIndexRoute
  AuthenticatedAdminUniversitiesIndexRoute: typeof AuthenticatedAdminUniversitiesIndexRoute
  AuthenticatedAdminVideosIndexRoute: typeof AuthenticatedAdminVideosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCoursesAddRoute: AuthenticatedAdminCoursesAddRoute,
  AuthenticatedAdminMaterialsAddRoute: AuthenticatedAdminMaterialsAddRoute,
  AuthenticatedAdminPapersAddRoute: AuthenticatedAdminPapersAddRoute,
  AuthenticatedAdminQuestionsAddRoute: AuthenticatedAdminQuestionsAddRoute,
  AuthenticatedAdminSemestersAddRoute: AuthenticatedAdminSemestersAddRoute,
  AuthenticatedAdminSubjectsAddRoute: AuthenticatedAdminSubjectsAddRoute,
  AuthenticatedAdminTimetablesAddRoute: AuthenticatedAdminTimetablesAddRoute,
  AuthenticatedAdminUnitsAddRoute: AuthenticatedAdminUnitsAddRoute,
  AuthenticatedAdminUniversitiesAddRoute:
    AuthenticatedAdminUniversitiesAddRoute,
  AuthenticatedAdminVideosAddRoute: AuthenticatedAdminVideosAddRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  AuthenticatedAdminMaterialsIndexRoute: AuthenticatedAdminMaterialsIndexRoute,
  AuthenticatedAdminPapersIndexRoute: AuthenticatedAdminPapersIndexRoute,
  AuthenticatedAdminQuestionsIndexRoute: AuthenticatedAdminQuestionsIndexRoute,
  AuthenticatedAdminSemestersIndexRoute: AuthenticatedAdminSemestersIndexRoute,
  AuthenticatedAdminSubjectsIndexRoute: AuthenticatedAdminSubjectsIndexRoute,
  AuthenticatedAdminTimetablesIndexRoute:
    AuthenticatedAdminTimetablesIndexRoute,
  AuthenticatedAdminUnitsIndexRoute: AuthenticatedAdminUnitsIndexRoute,
  AuthenticatedAdminUniversitiesIndexRoute:
    AuthenticatedAdminUniversitiesIndexRoute,
  AuthenticatedAdminVideosIndexRoute: AuthenticatedAdminVideosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentBookmarksRoute: typeof AuthenticatedStudentBookmarksRoute
  AuthenticatedStudentFullscreenTestRoute: typeof AuthenticatedStudentFullscreenTestRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentResumeRoute: typeof AuthenticatedStudentResumeRoute
  AuthenticatedStudentSearchRoute: typeof AuthenticatedStudentSearchRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentArenaIdRoute: typeof AuthenticatedStudentArenaIdRoute
  AuthenticatedStudentCourseIdRoute: typeof AuthenticatedStudentCourseIdRoute
  AuthenticatedStudentSemesterIdRoute: typeof AuthenticatedStudentSemesterIdRoute
  AuthenticatedStudentSubjectIdRoute: typeof AuthenticatedStudentSubjectIdRoute
  AuthenticatedStudentUnitIdRoute: typeof AuthenticatedStudentUnitIdRoute
  AuthenticatedStudentUniversityIdRoute: typeof AuthenticatedStudentUniversityIdRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentBookmarksRoute: AuthenticatedStudentBookmarksRoute,
  AuthenticatedStudentFullscreenTestRoute:
    AuthenticatedStudentFullscreenTestRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentResumeRoute: AuthenticatedStudentResumeRoute,
  AuthenticatedStudentSearchRoute: AuthenticatedStudentSearchRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentArenaIdRoute: AuthenticatedStudentArenaIdRoute,
  AuthenticatedStudentCourseIdRoute: AuthenticatedStudentCourseIdRoute,
  AuthenticatedStudentSemesterIdRoute: AuthenticatedStudentSemesterIdRoute,
  AuthenticatedStudentSubjectIdRoute: AuthenticatedStudentSubjectIdRoute,
  AuthenticatedStudentUnitIdRoute: AuthenticatedStudentUnitIdRoute,
  AuthenticatedStudentUniversityIdRoute: AuthenticatedStudentUniversityIdRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
